### ISSUE TITLE
nmdc-server should expand curies via the schema, not in custom code

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-server#1298]
provide examples for @naglepuff

**Comment by mslarae13** [comment]
no clarity on where the curie expansion is being done without the schema.
@turbomam to expand on this issue to be actionable for specific targets that need corrected

**Comment by turbomam** [comment]
Here's how nmdc-schema does it

https://github.com/microbiomedata/nmdc-schema/blob/165ffabbddf049d05c521fbda5a2b715f7cd26d1/nmdc_schema/nmdc_materialized_patterns.yaml#L223-L225

```yaml
  gold:
    prefix_prefix: gold
    prefix_reference: 'https://bioregistry.io/gold:
```

which bioregistry resolves to the same URL base, https://gold.jgi.doe.gov/study?id=

https://bioregistry.io/registry/gold
