### ISSUE TITLE
Update process for using display hints directly from the schema

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#750]
Look into a process and verification that display hints from the schema are being utilized properly by the web UI. Specifically, we could look into doing this for the study metadata in the submission portal and ensure we are directly using display hints like the following in the UI:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/81305/179070799-b7ef98bc-bd12-455d-9ef9-80593e839353.png">

@turbomam @cmungall FYI.

**Comment by aclum** [comment]
Default to description and have a way of overwriting it. @turbomam will do this for env context terms using annotations.

**Comment by turbomam** [comment]
See here for existing examples:

https://github.com/microbiomedata/nmdc-schema/blob/1d24f0de0f7ad0e7c9ef11a6c83fc34ff2c21dbc/src/schema/core.yaml#L230-L258

**Comment by turbomam** [comment]
related?
- https://github.com/microbiomedata/nmdc-server/issues/1220

**Comment by dwinston** [comment]
[not directly addressing this issue, but noting here as related]

There may be an opportunity to spin out a separate “governance tier” for slot definitions for informal annotations, represented more dynamically e.g. as a database (“slotbase”?) rather than as a set of yaml files in a git repo.

prior art / reference: https://metadata.raid.org/en/latest/#core-extended-and-local-metadata-schema-components

**Comment by turbomam** [comment]
- do we want to have multiple kinds of annotations? what would their names be?
- how would kitware/nmdc-server access the values? easy with Python SchemaView()
- who is going to populate the values?
-

**Comment by turbomam** [comment]
Use alt_descriptions instead?

https://github.com/microbiomedata/berkeley-schema-fy24/pull/167

**Comment by turbomam** [comment]
actually `alt_descriptions` isn't the best choice. we do have `display_hint` `annotations` already. but I propose switching them all to `tool_tip` `annotations`.

**Comment by aclum** [comment]
So slot_usage.$SLOT.annotations.tool_tip.value?

**Comment by aclum** [comment]
@turbomam I don't see any examples in berkeley-schema-fy24 or nmdc-schema which illustrate your most recent suggestion.

**Comment by aclum** [comment]
Using https://github.com/microbiomedata/nmdc-schema/pull/2120 as an example for how this should be formatted.

**Comment by aclum** [comment]
Example of preferred way to model this:

```
    annotations:
      tool_tip:
        tag: tool_tip
        value: GOLD Ecosystem Classification paths describe the surroundings from which an environmental sample or an organism is collected.
        annotations:
          source: https://gold.jgi.doe.gov/ecosystem_classification
```
