### ISSUE TITLE
Current prefixes in schema

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-server#988]
see also
- https://github.com/microbiomedata/nmdc-server/pull/986

```shell
gen-prefix-map src/schema/nmdc.yaml | yq -P
```

```yaml
CAS: http://identifiers.org/cas/
CATH: http://identifiers.org/cath/
CHEBI: http://purl.obolibrary.org/obo/CHEBI_
CHEMBL.COMPOUND: http://identifiers.org/chembl.compound/
CHMO: http://purl.obolibrary.org/obo/CHMO_
COG: 'https://bioregistry.io/cog:'
Contaminant: http://example.org/contaminant/
DRUGBANK: http://identifiers.org/drugbank/
EC: 'https://bioregistry.io/eccode:'
EFO: http://www.ebi.ac.uk/efo/
EGGNOG: http://identifiers.org/eggnog/
FBcv: http://purl.obolibrary.org/obo/FBcv_
GO: http://purl.obolibrary.org/obo/GO_
HMDB: http://identifiers.org/hmdb/
ISA: http://example.com/isa/
KEGG.COMPOUND: http://identifiers.org/kegg.compound/
KEGG.ORTHOLOGY: http://identifiers.org/kegg.orthology/
KEGG.REACTION: http://identifiers.org/kegg.reaction/
KEGG_PATHWAY: http://identifiers.org/kegg.pathway/
MESH: http://identifiers.org/mesh/
MIXS: https://w3id.org/mixs/
MetaCyc: https://identifiers.org/metacyc.reaction/
MetaNetX: http://example.com/metanetx/
NCIT: http://purl.obolibrary.org/obo/NCIT_
OBI: http://purl.obolibrary.org/obo/OBI_
PANTHER.FAMILY: http://identifiers.org/panther.family/
PFAM: http://identifiers.org/pfam/
PR: http://purl.obolibrary.org/obo/PR_
PUBCHEM.COMPOUND: http://identifiers.org/pubchem.compound/
RHEA: http://identifiers.org/rhea/
RO: http://purl.obolibrary.org/obo/RO_
RetroRules: http://example.com/retrorules/
SEED: http://identifiers.org/seed/
SIO: http://semanticscience.org/resource/SIO_
SUPFAM: http://identifiers.org/supfam/
TIGRFAM: http://identifiers.org/tigrfam/
UniProtKB: https://identifiers.org/uniprot/
biolink: https://w3id.org/biolink/vocab/
dcterms: http://purl.org/dc/terms/
emsl: http://example.org/emsl_in_mongodb/
emsl.project: 'https://bioregistry.io/emsl.project:'
generic: https://example.com/generic/
gnps.task: 'https://bioregistry.io/gnps.task:'
gtpo: http://example.com/gtpo/
igsn: https://app.geosamples.org/sample/igsn/
jgi: http://example.com/jgi/
jgi.proposal: 'https://bioregistry.io/jgi.proposal:'
linkml: https://w3id.org/linkml/
mgnify.proj: 'https://identifiers.org/mgnify.proj:'
neon.identifier: http://example.org/neon/identifier/
neon.schema: http://example.org/neon/schema/
nmdc: https://w3id.org/nmdc/
prov: http://www.w3.org/ns/prov#
qud: http://qudt.org/1.1/schema/qudt#
rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
rdfs: http://www.w3.org/2000/01/rdf-schema#
schema: http://schema.org/
sio: http://semanticscience.org/resource/SIO_
skos: http://www.w3.org/2004/02/skos/core#
wgs84: http://www.w3.org/2003/01/geo/wgs84_pos#
xsd: http://www.w3.org/2001/XMLSchema#
CreditAssociation:
  '@id': prov:Association
DissolvingActivity:
  '@id': CHMO:0002773
MaterialSamplingActivity:
  '@id': OBI:0000744
PlannedProcess:
  '@id': OBI:0000011
```
